spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://114.55.134.155:3306/huice
    username: root
    password: root
server:
  port: 8888
snowflake:
  enable: true
