server:
  port: ${SERVER_PORT:8999}

spring:
  application:
    name: HUICE-file-service
  profiles:
    active: ${ACTIVE:dev}
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
      enabled: true
      file-size-threshold: 5MB
  mvc:
    static-path-pattern: /**
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://123.249.107.238:3306/huice
    username: root
    password: Welsir123456@
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
  redis:
    host: 123.249.107.238 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: Welsir123456@ # Redis服务器连接密码（默认为空）
    timeout: 3000ms # 连接超时时间（毫秒）
aliyun:
  oss:
    endpoint: ${ALIYUN_ENDPOINT:oss-cn-beijing.aliyuncs.com}
    accessKeyId: ${ALIYUN_ACCESSKEYID:LTAI5tMHEaJ68taausomjWAS}
    accessKeySecret: ${ALIYUN_ACCESSKEYSECRET:T3wt3Xxd3wgfWlrlhfmhlB6cq3PrFL}
    bucket: ${ALIYUN_BUCKET:welsir-test}
    bucket-private: ${BUCKET_PRIVATE:false}
oss:
  handler: ${OSS_HANDLER:aliyun}
file:
  logger:
    handler: ${Logger:slf4j}
    enable: true
